default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: recipe_app_developement
  username: postgres
  password: nabeel
  host: localhost

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
